<a href="https://colab.research.google.com/github/mrahma15/MyRepos/blob/main/Homework_1_Problem_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [185]:
import numpy as np 
import pandas as pd 
 
# Data Visualisation 
import matplotlib.pyplot as plt 

In [186]:
housing = pd.DataFrame(pd.read_csv("/content/drive/MyDrive/Google Colab data/Homework 1/Housing.csv")) 
housing.head()

price  area  bedrooms  ...  parking  prefarea furnishingstatus
0  13300000  7420         4  ...        2       yes        furnished
1  12250000  8960         4  ...        3        no        furnished
2  12250000  9960         3  ...        2       yes   semi-furnished
3  12215000  7500         4  ...        3       yes        furnished
4  11410000  7420         4  ...        2        no        furnished

[5 rows x 13 columns]

In [187]:
m = len(housing) 
m 

545

In [188]:
housing.shape 

(545, 13)

In [189]:
num_vars = ['area', 'bedrooms', 'bathrooms', 'stories', 'parking','price'] 
Newtrain = housing[num_vars] 
Newtrain.head() 

area  bedrooms  bathrooms  stories  parking     price
0  7420         4          2        3        2  13300000
1  8960         4          4        4        3  12250000
2  9960         3          2        2        2  12250000
3  7500         4          2        2        3  12215000
4  7420         4          1        2        2  11410000

In [190]:
X1 = Newtrain.values[:, 0]               
X2 = Newtrain.values[:, 1]                
X3 = Newtrain.values[:, 2]                
X4 = Newtrain.values[:, 3]               
X5 = Newtrain.values[:, 4] 
Y = Newtrain.values[:, 5]

print('X1 = ', X1[: 5]) 
print('X2 = ', X2[: 5])
print('X3 = ', X3[: 5])
print('X4 = ', X4[: 5])
print('X5 = ', X5[: 5])
print('Y = ', Y[: 5])

X1 =  [7420 8960 9960 7500 7420]
X2 =  [4 4 3 4 4]
X3 =  [2 4 2 2 1]
X4 =  [3 4 2 2 2]
X5 =  [2 3 2 3 2]
Y =  [13300000 12250000 12250000 12215000 11410000]


In [191]:
import torch
torch.set_printoptions(edgeitems=2, linewidth=75)

In [192]:
X1 = torch.tensor(X1)
X2 = torch.tensor(X2)
X3 = torch.tensor(X3)
X4 = torch.tensor(X4)
X5 = torch.tensor(X5)
Y = torch.tensor(Y)

In [193]:
def model(X1, X2, X3, X4, X5, w1, w2, w3, w4, w5, b):
  return w5*X5 + w4*X4 + w3*X3 + w2*X2 + w1*X1 + b

In [194]:
def loss_fn(Y_p, Y):
    squared_diffs = (Y_p - Y)**2
    return squared_diffs.mean()

In [195]:
w1 = torch.ones(())
w2 = torch.ones(())
w3 = torch.ones(())
w4 = torch.ones(())
w5 = torch.ones(())
b = torch.zeros(())

#t_p = model(t_u, w, b)
Y_p = model(X1, X2, X3, X4, X5, w1, w2, w3, w4, w5, b)
Y_p

tensor([ 7431.,  8975.,  9969.,  7511.,  7429.,  7509.,  8593., 16210.,
         8109.,  5760., 13208.,  6011.,  6559.,  3510.,  7807.,  6009.,
         6609.,  8511.,  4609.,  6428.,  4328.,  7163.,  8056.,  4568.,
         8809.,  6550.,  6009.,  8881.,  7961.,  5509.,  7486.,  7010.,
         4889.,  5969.,  6849.,  7011.,  7491.,  9012.,  6010.,  6011.,
         6556.,  6369.,  6491.,  6012.,  6011.,  6008.,  6010.,  6611.,
         4308.,  7446.,  7450.,  6334.,  6011.,  5161.,  6008.,  6007.,
        11448.,  9011.,  7691.,  6010.,  6008.,  8885.,  6249.,  6371.,
        11181.,  8888., 13205.,  7708.,  6006., 12100.,  4007.,  6010.,
         5028.,  6608.,  4047.,  4268.,  6428.,  6508.,  5707.,  6008.,
         6007.,  4008., 10507.,  6009.,  3768.,  8258.,  6677.,  3967.,
         7417.,  8592.,  5006.,  6756.,  4809.,  7209.,  6011.,  4110.,
         9006.,  6406.,  6608.,  6008.,  6606.,  5508.,  5510.,  6358.,
         5508.,  4508.,  5457.,  6427.,  3249.,  6624.,  6607., 

In [196]:
loss = loss_fn(Y_p, Y)
loss

tensor(2.6160e+13)

In [197]:
learning_rate = 1e-2
delta = 0.1

In [198]:
loss_rate_of_change_w5 = \
    (loss_fn(model(X1, X2, X3, X4, X5, w1, w2, w3, w4, w5 + delta, b), Y) - 
     loss_fn(model(X1, X2, X3, X4, X5, w1, w2, w3, w4, w5 - delta, b), Y)) / (2.0 * delta)

w5 = w5 - learning_rate * loss_rate_of_change_w5

In [199]:
loss_rate_of_change_w4 = \
    (loss_fn(model(X1, X2, X3, X4, X5, w1, w2, w3, w4 + delta, w5, b), Y) - 
     loss_fn(model(X1, X2, X3, X4, X5, w1, w2, w3, w4 - delta, w5, b), Y)) / (2.0 * delta)

w4 = w4 - learning_rate * loss_rate_of_change_w4

In [200]:
loss_rate_of_change_w3 = \
    (loss_fn(model(X1, X2, X3, X4, X5, w1, w2, w3 + delta, w4, w5, b), Y) - 
     loss_fn(model(X1, X2, X3, X4, X5, w1, w2, w3 - delta, w4, w5, b), Y)) / (2.0 * delta)

w3 = w3 - learning_rate * loss_rate_of_change_w3

In [201]:
from torch._C import DeserializationStorageContext
loss_rate_of_change_w2 = \
    (loss_fn(model(X1, X2, X3, X4, X5, w1, w2 + delta, w3, w4, w5, b), Y) - 
     loss_fn(model(X1, X2, X3, X4, X5, w1, w2 - delta, w3, w4, w5, b), Y)) / (2.0 * delta)

w2 = w2 - learning_rate * loss_rate_of_change_w2

In [202]:
loss_rate_of_change_w1 = \
    (loss_fn(model(X1, X2, X3, X4, X5, w1 + delta, w2, w3, w4, w5, b), Y) - 
     loss_fn(model(X1, X2, X3, X4, X5, w1 - delta, w2, w3, w4, w5, b), Y)) / (2.0 * delta)

w1 = w1 - learning_rate * loss_rate_of_change_w1

In [203]:
loss_rate_of_change_b = \
    (loss_fn(model(X1, X2, X3, X4, X5, w1, w2, w3, w4, w5, b + delta), Y) - 
     loss_fn(model(X1, X2, X3, X4, X5, w1, w2, w3, w4, w5, b - delta), Y)) / (2.0 * delta)

b = b - learning_rate * loss_rate_of_change_b

In [204]:
def dloss_fn(Y_p, Y):
    dsq_diffs = 2 * (Y_p - Y) / Y_p.size(0)  # <1>
    return dsq_diffs

In [205]:
def dmodel_dw1(X1, X2, X3, X4, X5, w1, w2, w3, w4, w5, b):
    return X1

In [206]:
def dmodel_dw2(X1, X2, X3, X4, X5, w1, w2, w3, w4, w5, b):
    return X2

In [207]:
def dmodel_dw3(X1, X2, X3, X4, X5, w1, w2, w3, w4, w5, b):
    return X3

In [208]:
def dmodel_dw4(X1, X2, X3, X4, X5, w1, w2, w3, w4, w5, b):
    return X4

In [209]:
def dmodel_dw5(X1, X2, X3, X4, X5, w1, w2, w3, w4, w5, b):
    return X5

In [210]:
def dmodel_db(X1, X2, X3, X4, X5, w1, w2, w3, w4, w5, b):
    return 1.0

In [211]:
def grad_fn(X1, X2, X3, X4, X5, Y, Y_p, w1, w2, w3, w4, w5, b):
    dloss_dtp = dloss_fn(Y_p, Y)
    dloss_dw1 = dloss_dtp * dmodel_dw1(X1, X2, X3, X4, X5, w1, w2, w3, w4, w5, b)
    dloss_dw2 = dloss_dtp * dmodel_dw2(X1, X2, X3, X4, X5, w1, w2, w3, w4, w5, b)
    dloss_dw3 = dloss_dtp * dmodel_dw3(X1, X2, X3, X4, X5, w1, w2, w3, w4, w5, b)
    dloss_dw4 = dloss_dtp * dmodel_dw4(X1, X2, X3, X4, X5, w1, w2, w3, w4, w5, b)
    dloss_dw5 = dloss_dtp * dmodel_dw5(X1, X2, X3, X4, X5, w1, w2, w3, w4, w5, b)
    dloss_db = dloss_dtp * dmodel_db(X1, X2, X3, X4, X5, w1, w2, w3, w4, w5, b)
    return torch.stack([dloss_dw1.sum(), dloss_dw2.sum(), dloss_dw3.sum(), dloss_dw4.sum(), dloss_dw5.sum(), dloss_db.sum()])  # <1>

In [212]:
def training_loop(n_epochs, learning_rate, params, X1, X2, X3, X4, X5, Y):
    for epoch in range(1, n_epochs + 1):
        w1, w2, w3, w4, w5, b = params

        Y_p = model(X1, X2, X3, X4, X5, w1, w2, w3, w4, w5, b)  # <1>
        loss = loss_fn(Y_p, Y)
        grad = grad_fn(X1, X2, X3, X4, X5, Y, Y_p, w1, w2, w3, w4, w5, b)  # <2>

        params = params - learning_rate * grad

        print('Epoch %d, Loss %f' % (epoch, float(loss))) # <3>
            
    return params

In [213]:
def training_loop(n_epochs, learning_rate, params, X1, X2, X3, X4, X5, Y,
                  print_params=True):
    for epoch in range(1, n_epochs + 1):
        w1, w2, w3, w4, w5, b = params

        Y_p = model(X1, X2, X3, X4, X5, w1, w2, w3, w4, w5, b)  # <1>
        loss = loss_fn(Y_p, Y)
        grad = grad_fn(X1, X2, X3, X4, X5, Y, Y_p, w1, w2, w3, w4, w5, b)  # <2>

        params = params - learning_rate * grad

        if epoch in {1, 2, 3, 10, 11, 99, 100, 4000, 5000}:  # <3>
            print('Epoch %d, Loss %f' % (epoch, float(loss)))
            if print_params:
                print('    Params:', params)
                print('    Grad:  ', grad)
        if epoch in {4, 12, 101}:
            print('...')

        if not torch.isfinite(loss).all():
            break  # <3>
            
    return params

In [214]:
training_loop(
    n_epochs = 5000, 
    learning_rate = 1e-1, 
    params = torch.tensor([1.0, 1.0, 1.0, 1.0, 1.0, 0.0]), 
    X1 = X1,
    X2 = X2,
    X3 = X3, 
    X4 = X4,
    X5 = X5,  
    Y = Y)

Epoch 1, Loss 26160350101504.000000
    Params: tensor([5.3383e+09, 2.9247e+06, 1.3220e+06, 1.8557e+06, 7.8404e+05,
        9.5231e+05])
    Grad:   tensor([-5.3383e+10, -2.9247e+07, -1.3220e+07, -1.8557e+07, -7.8404e+06,
        -9.5231e+06])
Epoch 2, Loss 889955936712440423569686528.000000
    Params: tensor([-3.3342e+16, -1.6565e+13, -7.2983e+12, -1.0097e+13, -4.5174e+12,
        -5.4991e+12])
    Grad:   tensor([3.3342e+17, 1.6565e+14, 7.2983e+13, 1.0097e+14, 4.5174e+13,
        5.4991e+13])
Epoch 3, Loss inf
    Params: tensor([2.0825e+23, 1.0346e+20, 4.5584e+19, 6.3064e+19, 2.8215e+19,
        3.4346e+19])
    Grad:   tensor([-2.0825e+24, -1.0346e+21, -4.5584e+20, -6.3064e+20, -2.8215e+20,
        -3.4346e+20])


tensor([2.0825e+23, 1.0346e+20, 4.5584e+19, 6.3064e+19, 2.8215e+19,
        3.4346e+19])

In [215]:
training_loop(
    n_epochs = 5000, 
    learning_rate = 1e-2, 
    params = torch.tensor([1.0, 1.0, 1.0, 1.0, 1.0, 0.0]),  
    X1 = X1,
    X2 = X2,
    X3 = X3, 
    X4 = X4,
    X5 = X5,  
    Y = Y)

Epoch 1, Loss 26160350101504.000000
    Params: tensor([5.3383e+08, 2.9247e+05, 1.3220e+05, 1.8557e+05, 7.8405e+04,
        9.5231e+04])
    Grad:   tensor([-5.3383e+10, -2.9247e+07, -1.3220e+07, -1.8557e+07, -7.8404e+06,
        -9.5231e+06])
Epoch 2, Loss 8899533680033281595146240.000000
    Params: tensor([-3.3342e+14, -1.6565e+11, -7.2983e+10, -1.0097e+11, -4.5174e+10,
        -5.4990e+10])
    Grad:   tensor([3.3342e+16, 1.6565e+13, 7.2983e+12, 1.0097e+13, 4.5174e+12,
        5.4991e+12])
Epoch 3, Loss inf
    Params: tensor([2.0825e+20, 1.0346e+17, 4.5584e+16, 6.3064e+16, 2.8215e+16,
        3.4346e+16])
    Grad:   tensor([-2.0825e+22, -1.0346e+19, -4.5584e+18, -6.3064e+18, -2.8215e+18,
        -3.4346e+18])


tensor([2.0825e+20, 1.0346e+17, 4.5584e+16, 6.3064e+16, 2.8215e+16,
        3.4346e+16])

In [216]:
training_loop(
    n_epochs = 5000, 
    learning_rate = 1e-3, 
    params = torch.tensor([1.0, 1.0, 1.0, 1.0, 1.0, 0.0]), 
    X1 = X1,
    X2 = X2,
    X3 = X3, 
    X4 = X4,
    X5 = X5,  
    Y = Y)

Epoch 1, Loss 26160350101504.000000
    Params: tensor([5.3383e+07, 2.9248e+04, 1.3221e+04, 1.8558e+04, 7.8414e+03,
        9.5231e+03])
    Grad:   tensor([-5.3383e+10, -2.9247e+07, -1.3220e+07, -1.8557e+07, -7.8404e+06,
        -9.5231e+06])
Epoch 2, Loss 88992776954304618561536.000000
    Params: tensor([-3.3341e+12, -1.6564e+09, -7.2981e+08, -1.0097e+09, -4.5172e+08,
        -5.4989e+08])
    Grad:   tensor([3.3342e+15, 1.6564e+12, 7.2982e+11, 1.0097e+12, 4.5173e+11,
        5.4990e+11])
Epoch 3, Loss 347149103402845397579785366929408.000000
    Params: tensor([2.0824e+17, 1.0345e+14, 4.5582e+13, 6.3061e+13, 2.8213e+13,
        3.4344e+13])
    Grad:   tensor([-2.0824e+20, -1.0346e+17, -4.5582e+16, -6.3062e+16, -2.8214e+16,
        -3.4345e+16])
...


tensor([-1.3006e+22, -6.4615e+18, -2.8469e+18, -3.9386e+18, -1.7621e+18,
        -2.1450e+18])

In [217]:
training_loop(
    n_epochs = 5000, 
    learning_rate = 1e-4, 
    params = torch.tensor([1.0, 1.0, 1.0, 1.0, 1.0, 0.0]), 
    X1 = X1,
    X2 = X2,
    X3 = X3, 
    X4 = X4,
    X5 = X5,  
    Y = Y)

Epoch 1, Loss 26160350101504.000000
    Params: tensor([5.3383e+06, 2.9257e+03, 1.3230e+03, 1.8567e+03, 7.8504e+02,
        9.5231e+02])
    Grad:   tensor([-5.3383e+10, -2.9247e+07, -1.3220e+07, -1.8557e+07, -7.8404e+06,
        -9.5231e+06])
Epoch 2, Loss 889671328950764175360.000000
    Params: tensor([-3.3331e+10, -1.6559e+07, -7.2957e+06, -1.0093e+07, -4.5158e+06,
        -5.4972e+06])
    Grad:   tensor([3.3337e+14, 1.6562e+11, 7.2970e+10, 1.0095e+11, 4.5166e+10,
        5.4981e+10])
Epoch 3, Loss 34694886539256516770569125888.000000
    Params: tensor([2.0815e+14, 1.0341e+11, 4.5562e+10, 6.3034e+10, 2.8201e+10,
        3.4329e+10])
    Grad:   tensor([-2.0818e+18, -1.0343e+15, -4.5569e+14, -6.3044e+14, -2.8206e+14,
        -3.4335e+14])
...


tensor([-1.2998e+18, -6.4577e+14, -2.8453e+14, -3.9363e+14, -1.7611e+14,
        -2.1438e+14])