<a href="https://colab.research.google.com/github/mrahma15/MyRepos/blob/main/Homework_2_Problem_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
import torch
import torch.optim as optim

torch.set_printoptions(edgeitems=2, linewidth=75)

In [37]:
import numpy as np 
import pandas as pd  
import matplotlib.pyplot as plt 

In [38]:
housing = pd.DataFrame(pd.read_csv("/content/drive/MyDrive/Google Colab data/Homework 1/Housing.csv")) 
housing.head()

price  area  bedrooms  ...  parking  prefarea furnishingstatus
0  13300000  7420         4  ...        2       yes        furnished
1  12250000  8960         4  ...        3        no        furnished
2  12250000  9960         3  ...        2       yes   semi-furnished
3  12215000  7500         4  ...        3       yes        furnished
4  11410000  7420         4  ...        2        no        furnished

[5 rows x 13 columns]

In [39]:
num_vars = ['area', 'bedrooms', 'bathrooms', 'stories', 'parking','price'] 

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
housing[num_vars] = scaler.fit_transform(housing[num_vars])

Scaled_data = housing[num_vars] 
Scaled_data.head()

area  bedrooms  bathrooms   stories   parking     price
0  1.046726  1.403419   1.421812  1.378217  1.517692  4.566365
1  1.757010  1.403419   5.405809  2.532024  2.679409  4.004484
2  2.218232  0.047278   1.421812  0.224410  1.517692  4.004484
3  1.083624  1.403419   1.421812  0.224410  2.679409  3.985755
4  1.046726  1.403419  -0.570187  0.224410  1.517692  3.554979

In [40]:
y_Scaled = Scaled_data.pop('price')
X_Scaled = Scaled_data

In [41]:
X_Scaled.head()

area  bedrooms  bathrooms   stories   parking
0  1.046726  1.403419   1.421812  1.378217  1.517692
1  1.757010  1.403419   5.405809  2.532024  2.679409
2  2.218232  0.047278   1.421812  0.224410  1.517692
3  1.083624  1.403419   1.421812  0.224410  2.679409
4  1.046726  1.403419  -0.570187  0.224410  1.517692

In [42]:
y_Scaled.head()

0    4.566365
1    4.004484
2    4.004484
3    3.985755
4    3.554979
Name: price, dtype: float64

In [43]:
y_Scaled = torch.tensor(y_Scaled.values,dtype=torch.float).unsqueeze(1)


In [44]:
y_Scaled

tensor([[ 4.5664e+00],
        [ 4.0045e+00],
        [ 4.0045e+00],
        [ 3.9858e+00],
        [ 3.5550e+00],
        [ 3.2553e+00],
        [ 2.8807e+00],
        [ 2.8807e+00],
        [ 2.7309e+00],
        [ 2.6934e+00],
        [ 2.6934e+00],
        [ 2.6297e+00],
        [ 2.4312e+00],
        [ 2.3938e+00],
        [ 2.3938e+00],
        [ 2.3188e+00],
        [ 2.3188e+00],
        [ 2.2439e+00],
        [ 2.2065e+00],
        [ 2.1877e+00],
        [ 2.1315e+00],
        [ 2.0941e+00],
        [ 2.0754e+00],
        [ 2.0754e+00],
        [ 2.0379e+00],
        [ 2.0192e+00],
        [ 1.9780e+00],
        [ 1.9443e+00],
        [ 1.9443e+00],
        [ 1.9443e+00],
        [ 1.9443e+00],
        [ 1.9443e+00],
        [ 1.8881e+00],
        [ 1.8319e+00],
        [ 1.7944e+00],
        [ 1.7735e+00],
        [ 1.7532e+00],
        [ 1.7195e+00],
        [ 1.7101e+00],
        [ 1.6820e+00],
        [ 1.6633e+00],
        [ 1.6446e+00],
        [ 1.5697e+00],
        [ 1

In [45]:
X_Scaled = torch.tensor(X_Scaled.values,dtype=torch.float).unsqueeze(1)


In [46]:
X_Scaled

tensor([[[ 1.0467,  1.4034,  ...,  1.3782,  1.5177]],

        [[ 1.7570,  1.4034,  ...,  2.5320,  2.6794]],

        ...,

        [[-1.0334,  0.0473,  ..., -0.9294, -0.8057]],

        [[-0.5998,  0.0473,  ...,  0.2244, -0.8057]]])

In [47]:
n_samples = X_Scaled.shape[0]
n_val = int(0.2 * n_samples)

shuffled_indices = torch.randperm(n_samples)

train_indices = shuffled_indices[:-n_val]
val_indices = shuffled_indices[-n_val:]

train_indices, val_indices

(tensor([ 77, 455, 389,  56, 297,  89, 214, 366, 190, 503, 539, 456, 487,
         400, 406, 362, 453, 246,  43, 181,  30, 215, 521, 232, 118, 432,
         459, 409, 304,  23, 264, 394,  53, 161, 355, 413, 227, 419, 112,
         437,  75, 510, 356, 393,  11, 163, 320, 100, 136, 411, 375, 422,
          93, 540, 133, 324, 500, 200,  42, 179, 351, 517, 249, 388, 431,
         315, 262, 277,  64, 106, 263, 239,   0, 380,  52, 102, 450, 125,
         435, 188, 486,   3, 301, 328, 523, 519, 491,  45, 421, 266, 405,
         115, 282,  68,  41, 428,  87,  71, 383,  35, 184,  83, 302, 260,
         238, 467, 402, 466, 323,  99, 538, 316, 504, 240, 344,   7, 384,
         296, 311, 241, 349, 334, 354, 385, 242, 265, 458, 254, 485,  61,
         124, 206,  73, 146, 331, 525, 284, 505, 361, 391, 524, 299, 196,
         348, 272, 237, 253, 326, 204,  25, 113, 414, 248, 511, 329,  67,
         508, 279, 452,  47, 484, 399, 513, 195, 386, 482, 543, 229, 446,
         243, 268, 438, 153, 167, 465,

In [48]:
X_Train = X_Scaled[train_indices]
y_Train = y_Scaled[train_indices]

X_val = X_Scaled[val_indices]
y_val = y_Scaled[val_indices]

In [49]:
import torch.nn as nn

linear_model = nn.Linear(5, 1) # <1>
linear_model(X_val)

tensor([[[-0.5922]],

        [[-0.0707]],

        [[ 0.2739]],

        [[-0.3360]],

        [[-0.5375]],

        [[ 0.2127]],

        [[-0.6092]],

        [[ 0.5103]],

        [[-0.7909]],

        [[-0.8722]],

        [[-0.4507]],

        [[ 0.4049]],

        [[-0.2328]],

        [[ 0.0905]],

        [[-0.3971]],

        [[-0.6192]],

        [[ 0.0643]],

        [[-0.1287]],

        [[-0.0146]],

        [[ 0.4775]],

        [[ 0.1874]],

        [[ 0.1671]],

        [[ 0.6682]],

        [[-0.3511]],

        [[ 1.0283]],

        [[-1.6491]],

        [[-0.3414]],

        [[ 0.0385]],

        [[ 0.5312]],

        [[ 0.0612]],

        [[-0.2511]],

        [[ 0.1616]],

        [[-0.2642]],

        [[ 0.5936]],

        [[-0.3803]],

        [[ 0.2603]],

        [[ 0.5876]],

        [[-0.3369]],

        [[ 0.1938]],

        [[-0.2516]],

        [[-0.1425]],

        [[-0.0973]],

        [[-0.0023]],

        [[ 0.0965]],

        [[ 0.6832]],

        [[

In [50]:
linear_model.weight

Parameter containing:
tensor([[-0.3496, -0.2951,  0.0739,  0.1067,  0.2391]],
       requires_grad=True)

In [51]:
linear_model.bias

Parameter containing:
tensor([-0.0446], requires_grad=True)

In [52]:
x = torch.ones(5)
linear_model(x)

tensor([-0.2697], grad_fn=<AddBackward0>)

In [53]:
x = torch.ones(10, 5)
linear_model(x)

tensor([[-0.2697],
        [-0.2697],
        [-0.2697],
        [-0.2697],
        [-0.2697],
        [-0.2697],
        [-0.2697],
        [-0.2697],
        [-0.2697],
        [-0.2697]], grad_fn=<AddmmBackward0>)

In [54]:
linear_model = nn.Linear(5, 1) # <1>
optimizer = optim.SGD(
    linear_model.parameters(), # <2>
    lr=1e-2)

In [55]:
linear_model.parameters()

<generator object Module.parameters at 0x7fb9eb4eb050>

In [56]:
list(linear_model.parameters())

[Parameter containing:
 tensor([[-0.3876, -0.0527, -0.2747, -0.3256,  0.4338]],
        requires_grad=True), Parameter containing:
 tensor([0.0919], requires_grad=True)]

In [57]:
def training_loop(n_epochs, optimizer, model, loss_fn, X_Train, X_val,
                  y_Train, y_val):
    for epoch in range(1, n_epochs + 1):
        y_p_Train = model(X_Train) # <1>
        loss_train = loss_fn(y_p_Train, y_Train)

        t_p_val = model(X_val) # <1>
        loss_val = loss_fn(y_p_Train, y_val)
        
        optimizer.zero_grad()
        loss_train.backward() # <2>
        optimizer.step()

        if epoch == 1 or epoch % 20 == 0:
            print(f"Epoch {epoch}, Training loss {loss_train.item():.4f},"
                  f" Validation loss {loss_val.item():.4f}")

In [58]:
def loss_fn(y_p_Train, y_Train):
    squared_diffs = (y_p_Train - y_Train)**2
    return squared_diffs.mean()

linear_model = nn.Linear(5, 1) # <1>
optimizer = optim.SGD(linear_model.parameters(), lr=1e-2)

training_loop(
    n_epochs = 200, 
    optimizer = optimizer,
    model = linear_model,
    loss_fn = loss_fn,
    X_Train = X_Train,
    X_val = X_val, 
    y_Train = y_Train,
    y_val = y_val)

print()
print(linear_model.weight)
print(linear_model.bias)

Epoch 1, Training loss 1.5228, Validation loss 1.2975
Epoch 20, Training loss 1.2408, Validation loss 1.0323
Epoch 40, Training loss 1.1206, Validation loss 0.9237
Epoch 60, Training loss 1.0720, Validation loss 0.8827
Epoch 80, Training loss 1.0517, Validation loss 0.8673
Epoch 100, Training loss 1.0430, Validation loss 0.8618
Epoch 120, Training loss 1.0391, Validation loss 0.8600
Epoch 140, Training loss 1.0372, Validation loss 0.8595
Epoch 160, Training loss 1.0363, Validation loss 0.8595
Epoch 180, Training loss 1.0358, Validation loss 0.8596
Epoch 200, Training loss 1.0356, Validation loss 0.8598

Parameter containing:
tensor([[ 0.0016,  0.0025, -0.0153,  0.0144, -0.0005]],
       requires_grad=True)
Parameter containing:
tensor([0.0102], requires_grad=True)


In [59]:
linear_model = nn.Linear(5, 1)
optimizer = optim.SGD(linear_model.parameters(), lr=1e-2)

training_loop(
    n_epochs = 200, 
    optimizer = optimizer,
    model = linear_model,
    loss_fn = nn.MSELoss(), # <1>
    X_Train = X_Train,
    X_val = X_val, 
    y_Train = y_Train,
    y_val = y_val)

print()
print(linear_model.weight)
print(linear_model.bias)

Epoch 1, Training loss 1.4417, Validation loss 1.3166
Epoch 20, Training loss 1.2515, Validation loss 1.1114
Epoch 40, Training loss 1.1523, Validation loss 1.0012
Epoch 60, Training loss 1.1008, Validation loss 0.9422
Epoch 80, Training loss 1.0729, Validation loss 0.9091
Epoch 100, Training loss 1.0573, Validation loss 0.8900
Epoch 120, Training loss 1.0483, Validation loss 0.8786


/usr/local/lib/python3.7/dist-packages/torch/nn/modules/loss.py:520: UserWarning: Using a target size (torch.Size([436, 1])) that is different to the input size (torch.Size([436, 1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
/usr/local/lib/python3.7/dist-packages/torch/nn/modules/loss.py:520: UserWarning: Using a target size (torch.Size([109, 1])) that is different to the input size (torch.Size([436, 1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


Epoch 140, Training loss 1.0431, Validation loss 0.8717
Epoch 160, Training loss 1.0400, Validation loss 0.8675
Epoch 180, Training loss 1.0381, Validation loss 0.8648
Epoch 200, Training loss 1.0370, Validation loss 0.8632

Parameter containing:
tensor([[ 0.0061,  0.0394, -0.0331, -0.0034, -0.0070]],
       requires_grad=True)
Parameter containing:
tensor([0.0248], requires_grad=True)


In [60]:
seq_model = nn.Sequential(
            nn.Linear(5, 8), # <1>
            nn.Tanh(),
            nn.Linear(8, 1)) # <2>
seq_model

Sequential(
  (0): Linear(in_features=5, out_features=8, bias=True)
  (1): Tanh()
  (2): Linear(in_features=8, out_features=1, bias=True)
)

In [61]:
[param.shape for param in seq_model.parameters()]

[torch.Size([8, 5]), torch.Size([8]), torch.Size([1, 8]), torch.Size([1])]

In [62]:
for name, param in seq_model.named_parameters():
    print(name, param.shape)

0.weight torch.Size([8, 5])
0.bias torch.Size([8])
2.weight torch.Size([1, 8])
2.bias torch.Size([1])


In [63]:
from collections import OrderedDict

seq_model = nn.Sequential(OrderedDict([
    ('hidden_linear', nn.Linear(5, 8)),
    ('hidden_activation', nn.Tanh()),
    ('output_linear', nn.Linear(8, 1))
]))

seq_model

Sequential(
  (hidden_linear): Linear(in_features=5, out_features=8, bias=True)
  (hidden_activation): Tanh()
  (output_linear): Linear(in_features=8, out_features=1, bias=True)
)

In [64]:
for name, param in seq_model.named_parameters():
    print(name, param.shape)

hidden_linear.weight torch.Size([8, 5])
hidden_linear.bias torch.Size([8])
output_linear.weight torch.Size([1, 8])
output_linear.bias torch.Size([1])


In [65]:
seq_model.output_linear.bias

Parameter containing:
tensor([0.2726], requires_grad=True)

In [66]:
optimizer = optim.SGD(seq_model.parameters(), lr=1e-3) # <1>

training_loop(
    n_epochs = 200, 
    optimizer = optimizer,
    model = seq_model,
    loss_fn = nn.MSELoss(),
    X_Train = X_Train,
    X_val = X_val, 
    y_Train = y_Train,
    y_val = y_val)
    
print('output', seq_model(X_val))
print('answer', y_val)
print('hidden', seq_model.hidden_linear.weight.grad)

Epoch 1, Training loss 1.0688, Validation loss 0.8798
Epoch 20, Training loss 1.0664, Validation loss 0.8784
Epoch 40, Training loss 1.0642, Validation loss 0.8771
Epoch 60, Training loss 1.0623, Validation loss 0.8759
Epoch 80, Training loss 1.0605, Validation loss 0.8749


/usr/local/lib/python3.7/dist-packages/torch/nn/modules/loss.py:520: UserWarning: Using a target size (torch.Size([436, 1])) that is different to the input size (torch.Size([436, 1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
/usr/local/lib/python3.7/dist-packages/torch/nn/modules/loss.py:520: UserWarning: Using a target size (torch.Size([109, 1])) that is different to the input size (torch.Size([436, 1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


Epoch 100, Training loss 1.0589, Validation loss 0.8740
Epoch 120, Training loss 1.0575, Validation loss 0.8732
Epoch 140, Training loss 1.0561, Validation loss 0.8725
Epoch 160, Training loss 1.0550, Validation loss 0.8719
Epoch 180, Training loss 1.0539, Validation loss 0.8714
Epoch 200, Training loss 1.0529, Validation loss 0.8709
output tensor([[[-0.1014]],

        [[-0.2576]],

        [[ 0.0251]],

        [[-0.0724]],

        [[-0.1128]],

        [[ 0.0512]],

        [[-0.0385]],

        [[-0.1856]],

        [[-0.0466]],

        [[ 0.2480]],

        [[-0.0291]],

        [[-0.0971]],

        [[ 0.2014]],

        [[-0.0897]],

        [[-0.0252]],

        [[ 0.0935]],

        [[-0.0146]],

        [[-0.2010]],

        [[-0.0028]],

        [[ 0.0434]],

        [[-0.1290]],

        [[-0.0928]],

        [[-0.1488]],

        [[ 0.0061]],

        [[-0.0564]],

        [[-0.0056]],

        [[ 0.0076]],

        [[-0.0192]],

        [[-0.1819]],

        [[ 0.0153]]

In [67]:
#Problem 1b

seq_model = nn.Sequential(OrderedDict([
    ('hidden_linear_1', nn.Linear(5, 8)),
    ('hidden1_activation', nn.Tanh()),
    ('hidden_linear_2', nn.Linear(8, 4)),
    ('hidden2_activation', nn.Tanh()),
    ('hidden_linear_3', nn.Linear(4, 2)),
    ('hidden3_activation', nn.Tanh()),
    ('output_linear', nn.Linear(2, 1))
]))

seq_model

Sequential(
  (hidden_linear_1): Linear(in_features=5, out_features=8, bias=True)
  (hidden1_activation): Tanh()
  (hidden_linear_2): Linear(in_features=8, out_features=4, bias=True)
  (hidden2_activation): Tanh()
  (hidden_linear_3): Linear(in_features=4, out_features=2, bias=True)
  (hidden3_activation): Tanh()
  (output_linear): Linear(in_features=2, out_features=1, bias=True)
)

In [68]:
for name, param in seq_model.named_parameters():
    print(name, param.shape)

hidden_linear_1.weight torch.Size([8, 5])
hidden_linear_1.bias torch.Size([8])
hidden_linear_2.weight torch.Size([4, 8])
hidden_linear_2.bias torch.Size([4])
hidden_linear_3.weight torch.Size([2, 4])
hidden_linear_3.bias torch.Size([2])
output_linear.weight torch.Size([1, 2])
output_linear.bias torch.Size([1])


In [69]:
seq_model.output_linear.bias

Parameter containing:
tensor([-0.2168], requires_grad=True)

In [70]:
optimizer = optim.SGD(seq_model.parameters(), lr=1e-3) # <1>

training_loop(
    n_epochs = 200, 
    optimizer = optimizer,
    model = seq_model,
    loss_fn = nn.MSELoss(),
    X_Train = X_Train,
    X_val = X_val, 
    y_Train = y_Train,
    y_val = y_val)
    
print('output', seq_model(X_val))
print('answer', y_val)
#print('hidden', seq_model.hidden_linear.weight.grad)

Epoch 1, Training loss 1.0745, Validation loss 0.8709
Epoch 20, Training loss 1.0708, Validation loss 0.8686
Epoch 40, Training loss 1.0673, Validation loss 0.8665
Epoch 60, Training loss 1.0641, Validation loss 0.8647


/usr/local/lib/python3.7/dist-packages/torch/nn/modules/loss.py:520: UserWarning: Using a target size (torch.Size([436, 1])) that is different to the input size (torch.Size([436, 1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
/usr/local/lib/python3.7/dist-packages/torch/nn/modules/loss.py:520: UserWarning: Using a target size (torch.Size([109, 1])) that is different to the input size (torch.Size([436, 1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


Epoch 80, Training loss 1.0613, Validation loss 0.8631
Epoch 100, Training loss 1.0587, Validation loss 0.8618
Epoch 120, Training loss 1.0564, Validation loss 0.8606
Epoch 140, Training loss 1.0544, Validation loss 0.8596
Epoch 160, Training loss 1.0525, Validation loss 0.8588
Epoch 180, Training loss 1.0508, Validation loss 0.8581
Epoch 200, Training loss 1.0493, Validation loss 0.8575
output tensor([[[-0.1318]],

        [[-0.1156]],

        [[-0.1105]],

        [[-0.1236]],

        [[-0.1406]],

        [[-0.0777]],

        [[-0.1024]],

        [[-0.0558]],

        [[-0.0889]],

        [[-0.1070]],

        [[-0.0909]],

        [[-0.1066]],

        [[-0.0998]],

        [[-0.1319]],

        [[-0.0872]],

        [[-0.0858]],

        [[-0.1259]],

        [[-0.0988]],

        [[-0.0916]],

        [[-0.0935]],

        [[-0.0747]],

        [[-0.1255]],

        [[-0.0961]],

        [[-0.1067]],

        [[-0.0638]],

        [[-0.2191]],

        [[-0.1062]],

        