<a href="https://colab.research.google.com/github/mrahma15/MyRepos/blob/main/Homework_2_Problem_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.optim as optim

torch.set_printoptions(edgeitems=2, linewidth=75)

In [2]:
import numpy as np 
import pandas as pd  
import matplotlib.pyplot as plt 

In [3]:
housing = pd.DataFrame(pd.read_csv("/content/drive/MyDrive/Google Colab data/Homework 1/Housing.csv")) 
housing.head()

price  area  bedrooms  ...  parking  prefarea furnishingstatus
0  13300000  7420         4  ...        2       yes        furnished
1  12250000  8960         4  ...        3        no        furnished
2  12250000  9960         3  ...        2       yes   semi-furnished
3  12215000  7500         4  ...        3       yes        furnished
4  11410000  7420         4  ...        2        no        furnished

[5 rows x 13 columns]

In [4]:
num_vars = ['area', 'bedrooms', 'bathrooms', 'stories', 'parking','price'] 

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
housing[num_vars] = scaler.fit_transform(housing[num_vars])

Scaled_data = housing[num_vars] 
Scaled_data.head()

area  bedrooms  bathrooms   stories   parking     price
0  1.046726  1.403419   1.421812  1.378217  1.517692  4.566365
1  1.757010  1.403419   5.405809  2.532024  2.679409  4.004484
2  2.218232  0.047278   1.421812  0.224410  1.517692  4.004484
3  1.083624  1.403419   1.421812  0.224410  2.679409  3.985755
4  1.046726  1.403419  -0.570187  0.224410  1.517692  3.554979

In [5]:
y_Scaled = Scaled_data.pop('price')
X_Scaled = Scaled_data

In [6]:
X_Scaled.head()

area  bedrooms  bathrooms   stories   parking
0  1.046726  1.403419   1.421812  1.378217  1.517692
1  1.757010  1.403419   5.405809  2.532024  2.679409
2  2.218232  0.047278   1.421812  0.224410  1.517692
3  1.083624  1.403419   1.421812  0.224410  2.679409
4  1.046726  1.403419  -0.570187  0.224410  1.517692

In [7]:
y_Scaled.head()

0    4.566365
1    4.004484
2    4.004484
3    3.985755
4    3.554979
Name: price, dtype: float64

In [8]:
y_Scaled = torch.tensor(y_Scaled.values,dtype=torch.float).unsqueeze(1)


In [9]:
y_Scaled

tensor([[ 4.5664e+00],
        [ 4.0045e+00],
        [ 4.0045e+00],
        [ 3.9858e+00],
        [ 3.5550e+00],
        [ 3.2553e+00],
        [ 2.8807e+00],
        [ 2.8807e+00],
        [ 2.7309e+00],
        [ 2.6934e+00],
        [ 2.6934e+00],
        [ 2.6297e+00],
        [ 2.4312e+00],
        [ 2.3938e+00],
        [ 2.3938e+00],
        [ 2.3188e+00],
        [ 2.3188e+00],
        [ 2.2439e+00],
        [ 2.2065e+00],
        [ 2.1877e+00],
        [ 2.1315e+00],
        [ 2.0941e+00],
        [ 2.0754e+00],
        [ 2.0754e+00],
        [ 2.0379e+00],
        [ 2.0192e+00],
        [ 1.9780e+00],
        [ 1.9443e+00],
        [ 1.9443e+00],
        [ 1.9443e+00],
        [ 1.9443e+00],
        [ 1.9443e+00],
        [ 1.8881e+00],
        [ 1.8319e+00],
        [ 1.7944e+00],
        [ 1.7735e+00],
        [ 1.7532e+00],
        [ 1.7195e+00],
        [ 1.7101e+00],
        [ 1.6820e+00],
        [ 1.6633e+00],
        [ 1.6446e+00],
        [ 1.5697e+00],
        [ 1

In [10]:
X_Scaled = torch.tensor(X_Scaled.values,dtype=torch.float).unsqueeze(1)


In [11]:
X_Scaled

tensor([[[ 1.0467,  1.4034,  ...,  1.3782,  1.5177]],

        [[ 1.7570,  1.4034,  ...,  2.5320,  2.6794]],

        ...,

        [[-1.0334,  0.0473,  ..., -0.9294, -0.8057]],

        [[-0.5998,  0.0473,  ...,  0.2244, -0.8057]]])

In [12]:
n_samples = X_Scaled.shape[0]
n_val = int(0.2 * n_samples)

shuffled_indices = torch.randperm(n_samples)

train_indices = shuffled_indices[:-n_val]
val_indices = shuffled_indices[-n_val:]

train_indices, val_indices

(tensor([147,  36, 521, 304,  70,  87, 238, 171, 395, 407, 444,  54, 162,
         231, 198,  75, 152, 362, 414, 226, 451, 195, 100,   6, 435, 363,
         317, 182, 443, 396, 320, 271, 538, 300, 138,  60, 249, 316, 383,
         227, 259,  50, 223, 525,  98, 402, 289, 422, 434,  17,  10, 436,
         156,  44, 471, 269,  52, 517,  16, 281, 145,  64,  14,  79, 248,
          65, 181,   0, 394, 117, 369, 186, 461, 450,  86,  23,  11,  92,
         518, 107, 424, 233,  53, 385,   2, 282, 124, 243, 146, 151, 514,
         311, 345, 397, 367, 341, 532, 265, 361, 105, 157, 343, 506, 280,
         193, 329, 505, 273,  33, 203, 128, 427, 382, 246, 185, 481, 287,
         490, 326, 276,  13, 371, 260,  77,  35, 219, 500, 358, 499,  91,
         429, 489, 174, 493, 241, 468, 352, 194,  37, 188, 356, 488, 420,
          72, 507, 211, 155, 389, 366, 189, 115, 126, 131, 264,  28,   9,
         486, 103, 520, 274, 200, 144,  90, 355, 426, 168,  82, 332, 206,
         412, 177,  56, 175, 342, 365,

In [13]:
X_Train = X_Scaled[train_indices]
y_Train = y_Scaled[train_indices]

X_val = X_Scaled[val_indices]
y_val = y_Scaled[val_indices]

In [14]:
import torch.nn as nn

linear_model = nn.Linear(5, 1) # <1>
linear_model(X_val)

tensor([[[ 1.4894]],

        [[ 0.5062]],

        [[-1.6001]],

        [[ 0.9868]],

        [[ 0.7739]],

        [[ 1.1820]],

        [[ 0.4192]],

        [[ 2.0549]],

        [[ 0.9373]],

        [[ 0.2718]],

        [[ 0.7640]],

        [[ 0.0572]],

        [[-0.6659]],

        [[ 1.4311]],

        [[-0.9320]],

        [[ 0.3412]],

        [[-0.2781]],

        [[ 0.1761]],

        [[ 0.9535]],

        [[ 0.3979]],

        [[ 0.7985]],

        [[ 0.4016]],

        [[-0.2536]],

        [[ 1.3618]],

        [[ 1.3739]],

        [[ 0.1250]],

        [[ 0.6941]],

        [[ 1.2751]],

        [[ 0.6577]],

        [[ 1.4051]],

        [[-0.1432]],

        [[ 0.4199]],

        [[ 0.4205]],

        [[ 0.4091]],

        [[-0.2125]],

        [[-0.5635]],

        [[ 0.6152]],

        [[ 0.5048]],

        [[ 0.2346]],

        [[ 0.4103]],

        [[ 0.6856]],

        [[ 0.4551]],

        [[ 1.4254]],

        [[-0.6506]],

        [[ 0.9091]],

        [[

In [15]:
linear_model.weight

Parameter containing:
tensor([[-0.3759, -0.4408, -0.0008, -0.1147, -0.1520]],
       requires_grad=True)

In [16]:
linear_model.bias

Parameter containing:
tensor([0.3559], requires_grad=True)

In [17]:
x = torch.ones(5)
linear_model(x)

tensor([-0.7282], grad_fn=<AddBackward0>)

In [18]:
x = torch.ones(10, 5)
linear_model(x)

tensor([[-0.7282],
        [-0.7282],
        [-0.7282],
        [-0.7282],
        [-0.7282],
        [-0.7282],
        [-0.7282],
        [-0.7282],
        [-0.7282],
        [-0.7282]], grad_fn=<AddmmBackward0>)

In [19]:
linear_model = nn.Linear(5, 1) # <1>
optimizer = optim.SGD(
    linear_model.parameters(), # <2>
    lr=1e-2)

In [20]:
linear_model.parameters()

<generator object Module.parameters at 0x7fb9ebddbdd0>

In [21]:
list(linear_model.parameters())

[Parameter containing:
 tensor([[-0.2836,  0.1755, -0.3297, -0.2450, -0.4403]],
        requires_grad=True), Parameter containing:
 tensor([0.0489], requires_grad=True)]

In [22]:
def training_loop(n_epochs, optimizer, model, loss_fn, X_Train, X_val,
                  y_Train, y_val):
    for epoch in range(1, n_epochs + 1):
        y_p_Train = model(X_Train) # <1>
        loss_train = loss_fn(y_p_Train, y_Train)

        t_p_val = model(X_val) # <1>
        loss_val = loss_fn(y_p_Train, y_val)
        
        optimizer.zero_grad()
        loss_train.backward() # <2>
        optimizer.step()

        if epoch == 1 or epoch % 20 == 0:
            print(f"Epoch {epoch}, Training loss {loss_train.item():.4f},"
                  f" Validation loss {loss_val.item():.4f}")

In [23]:
def loss_fn(y_p_Train, y_Train):
    squared_diffs = (y_p_Train - y_Train)**2
    return squared_diffs.mean()

linear_model = nn.Linear(5, 1) # <1>
optimizer = optim.SGD(linear_model.parameters(), lr=1e-2)

training_loop(
    n_epochs = 200, 
    optimizer = optimizer,
    model = linear_model,
    loss_fn = loss_fn,
    X_Train = X_Train,
    X_val = X_val, 
    y_Train = y_Train,
    y_val = y_val)

print()
print(linear_model.weight)
print(linear_model.bias)

Epoch 1, Training loss 1.4981, Validation loss 1.5341
Epoch 20, Training loss 1.2135, Validation loss 1.2046
Epoch 40, Training loss 1.0972, Validation loss 1.0580
Epoch 60, Training loss 1.0524, Validation loss 0.9940
Epoch 80, Training loss 1.0347, Validation loss 0.9641
Epoch 100, Training loss 1.0274, Validation loss 0.9490
Epoch 120, Training loss 1.0243, Validation loss 0.9410
Epoch 140, Training loss 1.0229, Validation loss 0.9364
Epoch 160, Training loss 1.0222, Validation loss 0.9336
Epoch 180, Training loss 1.0218, Validation loss 0.9320
Epoch 200, Training loss 1.0217, Validation loss 0.9310

Parameter containing:
tensor([[ 0.0034,  0.0060,  0.0078, -0.0153, -0.0045]],
       requires_grad=True)
Parameter containing:
tensor([0.0570], requires_grad=True)


In [24]:
linear_model = nn.Linear(5, 1)
optimizer = optim.SGD(linear_model.parameters(), lr=1e-2)

training_loop(
    n_epochs = 200, 
    optimizer = optimizer,
    model = linear_model,
    loss_fn = nn.MSELoss(), # <1>
    X_Train = X_Train,
    X_val = X_val, 
    y_Train = y_Train,
    y_val = y_val)

print()
print(linear_model.weight)
print(linear_model.bias)

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/loss.py:520: UserWarning: Using a target size (torch.Size([436, 1])) that is different to the input size (torch.Size([436, 1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
/usr/local/lib/python3.7/dist-packages/torch/nn/modules/loss.py:520: UserWarning: Using a target size (torch.Size([109, 1])) that is different to the input size (torch.Size([436, 1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


Epoch 1, Training loss 1.3485, Validation loss 1.1479
Epoch 20, Training loss 1.1626, Validation loss 0.9927
Epoch 40, Training loss 1.0821, Validation loss 0.9357
Epoch 60, Training loss 1.0487, Validation loss 0.9189
Epoch 80, Training loss 1.0343, Validation loss 0.9161
Epoch 100, Training loss 1.0278, Validation loss 0.9177
Epoch 120, Training loss 1.0247, Validation loss 0.9202
Epoch 140, Training loss 1.0232, Validation loss 0.9226
Epoch 160, Training loss 1.0224, Validation loss 0.9244
Epoch 180, Training loss 1.0220, Validation loss 0.9258
Epoch 200, Training loss 1.0217, Validation loss 0.9268

Parameter containing:
tensor([[-0.0011, -0.0144, -0.0019,  0.0135,  0.0090]],
       requires_grad=True)
Parameter containing:
tensor([0.0494], requires_grad=True)


In [25]:
seq_model = nn.Sequential(
            nn.Linear(5, 8), # <1>
            nn.Tanh(),
            nn.Linear(8, 1)) # <2>
seq_model

Sequential(
  (0): Linear(in_features=5, out_features=8, bias=True)
  (1): Tanh()
  (2): Linear(in_features=8, out_features=1, bias=True)
)

In [26]:
[param.shape for param in seq_model.parameters()]

[torch.Size([8, 5]), torch.Size([8]), torch.Size([1, 8]), torch.Size([1])]

In [27]:
for name, param in seq_model.named_parameters():
    print(name, param.shape)

0.weight torch.Size([8, 5])
0.bias torch.Size([8])
2.weight torch.Size([1, 8])
2.bias torch.Size([1])


In [28]:
from collections import OrderedDict

seq_model = nn.Sequential(OrderedDict([
    ('hidden_linear', nn.Linear(5, 8)),
    ('hidden_activation', nn.Tanh()),
    ('output_linear', nn.Linear(8, 1))
]))

seq_model

Sequential(
  (hidden_linear): Linear(in_features=5, out_features=8, bias=True)
  (hidden_activation): Tanh()
  (output_linear): Linear(in_features=8, out_features=1, bias=True)
)

In [29]:
for name, param in seq_model.named_parameters():
    print(name, param.shape)

hidden_linear.weight torch.Size([8, 5])
hidden_linear.bias torch.Size([8])
output_linear.weight torch.Size([1, 8])
output_linear.bias torch.Size([1])


In [30]:
seq_model.output_linear.bias

Parameter containing:
tensor([-0.1921], requires_grad=True)

In [31]:
optimizer = optim.SGD(seq_model.parameters(), lr=1e-3) # <1>

training_loop(
    n_epochs = 200, 
    optimizer = optimizer,
    model = seq_model,
    loss_fn = nn.MSELoss(),
    X_Train = X_Train,
    X_val = X_val, 
    y_Train = y_Train,
    y_val = y_val)
    
print('output', seq_model(X_val))
print('answer', y_val)
print('hidden', seq_model.hidden_linear.weight.grad)

Epoch 1, Training loss 1.0814, Validation loss 0.9329
Epoch 20, Training loss 1.0780, Validation loss 0.9323
Epoch 40, Training loss 1.0746, Validation loss 0.9318
Epoch 60, Training loss 1.0715, Validation loss 0.9313
Epoch 80, Training loss 1.0686, Validation loss 0.9309


/usr/local/lib/python3.7/dist-packages/torch/nn/modules/loss.py:520: UserWarning: Using a target size (torch.Size([436, 1])) that is different to the input size (torch.Size([436, 1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
/usr/local/lib/python3.7/dist-packages/torch/nn/modules/loss.py:520: UserWarning: Using a target size (torch.Size([109, 1])) that is different to the input size (torch.Size([436, 1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


Epoch 100, Training loss 1.0660, Validation loss 0.9306
Epoch 120, Training loss 1.0635, Validation loss 0.9303
Epoch 140, Training loss 1.0612, Validation loss 0.9301
Epoch 160, Training loss 1.0590, Validation loss 0.9299
Epoch 180, Training loss 1.0570, Validation loss 0.9297
Epoch 200, Training loss 1.0551, Validation loss 0.9296
output tensor([[[-2.5791e-01]],

        [[-1.4784e-01]],

        [[ 1.8362e-01]],

        [[ 3.3998e-03]],

        [[-8.3127e-02]],

        [[-1.1591e-01]],

        [[ 6.5978e-02]],

        [[-2.2669e-01]],

        [[-2.4383e-01]],

        [[ 7.8196e-02]],

        [[-2.1870e-01]],

        [[-8.0256e-02]],

        [[-5.0012e-02]],

        [[-2.4898e-01]],

        [[ 3.5721e-01]],

        [[ 8.3120e-02]],

        [[ 4.0530e-03]],

        [[-1.2942e-01]],

        [[-2.4665e-02]],

        [[-1.3097e-01]],

        [[ 3.2843e-02]],

        [[ 1.0685e-01]],

        [[-8.4290e-02]],

        [[-2.3724e-01]],

        [[-2.3939e-01]],

       

In [32]:
#Problem 1b

seq_model = nn.Sequential(OrderedDict([
    ('hidden_linear_1', nn.Linear(5, 8)),
    ('hidden1_activation', nn.Tanh()),
    ('hidden_linear_2', nn.Linear(8, 4)),
    ('hidden2_activation', nn.Tanh()),
    ('hidden_linear_3', nn.Linear(4, 2)),
    ('hidden2_activation', nn.Tanh()),
    ('output_linear', nn.Linear(2, 1))
]))

seq_model

Sequential(
  (hidden_linear_1): Linear(in_features=5, out_features=8, bias=True)
  (hidden1_activation): Tanh()
  (hidden_linear_2): Linear(in_features=8, out_features=4, bias=True)
  (hidden2_activation): Tanh()
  (hidden_linear_3): Linear(in_features=4, out_features=2, bias=True)
  (output_linear): Linear(in_features=2, out_features=1, bias=True)
)

In [33]:
for name, param in seq_model.named_parameters():
    print(name, param.shape)

hidden_linear_1.weight torch.Size([8, 5])
hidden_linear_1.bias torch.Size([8])
hidden_linear_2.weight torch.Size([4, 8])
hidden_linear_2.bias torch.Size([4])
hidden_linear_3.weight torch.Size([2, 4])
hidden_linear_3.bias torch.Size([2])
output_linear.weight torch.Size([1, 2])
output_linear.bias torch.Size([1])


In [34]:
seq_model.output_linear.bias

Parameter containing:
tensor([-0.6456], requires_grad=True)

In [35]:
optimizer = optim.SGD(seq_model.parameters(), lr=1e-3) # <1>

training_loop(
    n_epochs = 200, 
    optimizer = optimizer,
    model = seq_model,
    loss_fn = nn.MSELoss(),
    X_Train = X_Train,
    X_val = X_val, 
    y_Train = y_Train,
    y_val = y_val)
    
print('output', seq_model(X_val))
print('answer', y_val)
#print('hidden', seq_model.hidden_linear.weight.grad)

Epoch 1, Training loss 1.4307, Validation loss 0.9913
Epoch 20, Training loss 1.3799, Validation loss 0.9628
Epoch 40, Training loss 1.3331, Validation loss 0.9381
Epoch 60, Training loss 1.2923, Validation loss 0.9179


/usr/local/lib/python3.7/dist-packages/torch/nn/modules/loss.py:520: UserWarning: Using a target size (torch.Size([436, 1])) that is different to the input size (torch.Size([436, 1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
/usr/local/lib/python3.7/dist-packages/torch/nn/modules/loss.py:520: UserWarning: Using a target size (torch.Size([109, 1])) that is different to the input size (torch.Size([436, 1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


Epoch 80, Training loss 1.2566, Validation loss 0.9015
Epoch 100, Training loss 1.2255, Validation loss 0.8886
Epoch 120, Training loss 1.1984, Validation loss 0.8784
Epoch 140, Training loss 1.1747, Validation loss 0.8707
Epoch 160, Training loss 1.1542, Validation loss 0.8650
Epoch 180, Training loss 1.1363, Validation loss 0.8610
Epoch 200, Training loss 1.1207, Validation loss 0.8585
output tensor([[[-0.2800]],

        [[-0.2504]],

        [[-0.3205]],

        [[-0.2590]],

        [[-0.2547]],

        [[-0.2288]],

        [[-0.1700]],

        [[-0.2522]],

        [[-0.2989]],

        [[-0.2333]],

        [[-0.3096]],

        [[-0.2745]],

        [[-0.2509]],

        [[-0.2827]],

        [[-0.1676]],

        [[-0.1741]],

        [[-0.1996]],

        [[-0.2735]],

        [[-0.2166]],

        [[-0.2561]],

        [[-0.2094]],

        [[-0.2045]],

        [[-0.2636]],

        [[-0.2861]],

        [[-0.2855]],

        [[-0.3412]],

        [[-0.2596]],

        